# =============================================================================
# 参考脚本（从博客原文收集 · 未运行验证 · 原文代码块被压成单行）
# 来源文章: articles/20261001-晶胞转换_天帝君豪的个人博客.md
# 原文链接: https://tiandijunhao.github.io/2020/04/25/jing-bao-zhuan-huan/
# 作者    : 天帝君豪
# 用途    : 用 spglib.standardize_cell 把胞标准化：`to_primitive=False` → **惯用胞**；`to_primitive=True` → **原胞**；再按元素重排坐标并写出 `RECELL`
# 依赖    : Python + spglib + numpy
# 抓取质量: 原网页代码块**丢失换行与缩进**（整段挤成一行），逻辑可读但**不能直接复制运行**；
#           如需使用请按 Python 语法重新缩进。
# 注意    : 关键调用：`spglib.standardize_cell(cell=(lattice, positions, numbers), symprec=1e-3, to_primitive=...)`；输出文件头写作 `recell_poscar`，坐标类型写 `DIRECT`。
# =============================================================================

import os import numpy as np import read_poscar as readpos import spglib classrecell(object):def__init__( self, spg_num=None, lattindex=None, latt=None, atomname=None, atomnum=None, postype=None, position=None, cell_lattice=None, cell_position=None, cell_atomnum=None, to_pricell = None ):# read the origmitive cell self.spg_num = readpos.read_poscar().spacegroup_num() self.lattindex = readpos.read_poscar().latt_index() self.latt = readpos.read_poscar().latti() self.atomname = readpos.read_poscar().atom_name() self.atomnum = readpos.read_poscar().atom_number() self.postype = readpos.read_poscar().position_type() self.position = readpos.read_poscar().positions() orignumbers =[]for i in np.arange(0, len(self.atomname)):for j in np.arange(0, int(self.atomnum[i]),1): orignumbers.append(i +1) origlattice = self.latt * self.lattindex origpositon = self.position origcell =(origlattice, origpositon, orignumbers)if(to_pricell==False):# refine cell self.cell_lattice, re_position, re_numbers = spglib.standardize_cell( cell=origcell, symprec=1e-3, to_primitive=False)else: self.cell_lattice, re_position, re_numbers = spglib.standardize_cell( cell=origcell, symprec=1e-3, to_primitive=True)# 主要对坐标进行重新排序 re_position_list = list(re_position) zipped = list(zip(re_numbers, re_position_list)) zipsorted = sorted(zipped, key=lambda x:(x[0])) re_numbers_sort, re_positon_sort = zip(*zipsorted) self.cell_position = np.array(re_positon_sort) self.cell_atomnum =[]for i in np.arange(0, len(self.atomnum),1): num = int(self.atomnum[i])*(len(re_numbers_sort)/ len(orignumbers)) self.cell_atomnum.append(num)# write the refine cell writepos = open("RECELL", mode="w")print("recell_poscar", file=writepos)print("1.0", file=writepos)for m in np.arange(0,3,1):print( format(self.cell_lattice[m,0],".10f")," ", format(self.cell_lattice[m,1],".10f")," ", format(self.cell_lattice[m,2],".10f"), file=writepos,)for j in np.arange(0, len(self.atomname),1):print(self.atomname[j], file=writepos, end=" ")print(end="\n", file=writepos)for l in np.arange(0, len(self.atomname),1):print(int(self.cell_atomnum[l]), end=" ", file=writepos)print(end="\n", file=writepos)print(self.postype[0], file=writepos)for n in np.arange(0, self.cell_position.shape[0],1):print( format(self.cell_position[n,0],".10f")," ", format(self.cell_position[n,1],".10f")," ", format(self.cell_position[n,2],".10f"), file=writepos,) writepos.close()deflatti(self):return self.cell_lattice defatom_number(self):return self.cell_atomnum defpositions(self):return self.cell_position
